
name: Build on Windows

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-2025

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B -e -ntp install
